name: Trigger Azure ML Notebook Daily at 8 AM

on:
  schedule:
    - cron: '30 5 * * *'  # This triggers at 5.30 AM UTC every day
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  trigger-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Azure ML SDK
      run: |
        python -m pip install --upgrade pip
        pip install azureml-sdk

    - name: Authenticate to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Trigger Notebook Execution in Azure ML
      run: |
        python trigger_notebook.py
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
